# (generated with --quick)

from typing import Any, Set, Union

REMOTE_SESSION_KEY: str
clients: module
django: module
models: module

class KeycloakAuthorization:
    def authenticate(self, request, code, redirect_uri) -> Any: ...
    def get_all_permissions(self, user_obj, obj = ...) -> Union[list, Set[nothing]]: ...
    def get_keycloak_permissions(self, user_obj) -> Union[list, Set[nothing]]: ...
    def get_user(self, user_id) -> None: ...
    def has_module_perms(self, user_obj, model) -> bool: ...
    def has_perm(self, user_obj, perm, obj = ...) -> bool: ...

def _get_user_session_key(request) -> str: ...
def get_remote_user(session) -> Any: ...
def remote_user_login(request, user, backend = ...) -> None: ...
