# (generated with --quick)

from typing import Any

close_old_connections: Any
django: module
keycloak_auth: module

class OIDCChannelsMiddleware:
    def __call__(self, scope) -> Any: ...
    def __init__(self, inner) -> None: ...
    def inner(self, _1: dict) -> Any: ...

class OIDCMiddleware:
    def __call__(self, request) -> Any: ...
    def __init__(self, get_response) -> None: ...
    def get_response(self, _1) -> Any: ...

def get_user(session, origin_user) -> Any: ...
