FROM python:3.6-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev python3-dev && \
 python3 -m pip install rasa tensorflow~=1.15.0 psycopg2 && apt-get purge -y build-essential && apt-get -y autoremove --purge

WORKDIR /app

ENTRYPOINT ["rasa"]