FROM python:3.7-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y build-essential libpq-dev python-dev && pip install rasa tensorflow~=1.15.0 psycopg2 && apt-get purge -y build-essential

WORKDIR /app

ENTRYPOINT ["rasa"]