# Generated by Django 2.1.3 on 2019-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter')], max_length=2)),
                ('platform_id', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=255)),
            ],
        ),
    ]
