# Generated by Django 3.0.4 on 2020-03-11 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operator_interface', '0049_auto_20200311_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkingState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account_linking_state', to='operator_interface.ConversationPlatform')),
            ],
        ),
    ]
