# Generated by Django 2.2.1 on 2019-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0002_message_timestamp")]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="noonce",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        )
    ]
