# Generated by Django 2.2.1 on 2019-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0003_conversation_noonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
