# Generated by Django 2.2.1 on 2019-05-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0006_auto_20190521_1056")]

    operations = [
        migrations.CreateModel(
            name="ConversationRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operator_interface.Conversation",
                    ),
                ),
            ],
        )
    ]
