# Generated by Django 2.2.1 on 2019-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0012_auto_20190615_1011")]

    operations = [
        migrations.RemoveField(model_name="conversationrating", name="conversation"),
        migrations.AddField(
            model_name="conversationrating",
            name="sender_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
