# Generated by Django 2.2.1 on 2019-08-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0013_auto_20190801_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='noonce',
        ),
    ]
