# Generated by Django 2.2.1 on 2019-08-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190806_1359'),
        ('operator_interface', '0020_auto_20190807_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='payment_confirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirm_message', to='payment.Payment'),
        ),
        migrations.AddField(
            model_name='message',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_message', to='payment.Payment'),
        ),
        migrations.DeleteModel(
            name='PaymentConfirmMessage',
        ),
        migrations.DeleteModel(
            name='PaymentMessage',
        ),
    ]
