# Generated by Django 2.2.1 on 2019-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0024_message_delivered")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="request_phone",
            field=models.BooleanField(default=False),
        )
    ]
