# Generated by Django 2.2.4 on 2019-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0027_auto_20190831_1627")]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="noonce",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="platform_from_id",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
