# Generated by Django 2.2.4 on 2019-08-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0028_auto_20190831_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='noonce',
        ),
    ]
