# Generated by Django 2.2.4 on 2019-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0030_message_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='end',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='request_phone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
