# Generated by Django 2.2.4 on 2019-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0031_auto_20190831_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request_name',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
