# Generated by Django 2.2.4 on 2019-09-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0036_auto_20190902_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='form_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
