# Generated by Django 2.2.1 on 2019-09-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("operator_interface", "0039_conversation_customer_user_id")]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="customer_name",
            new_name="conversation_name",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="customer_pic",
            new_name="conversation_pic",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="customer_user_id",
            new_name="conversation_user_id",
        ),
        migrations.RemoveField(model_name="conversation", name="customer_email"),
        migrations.RemoveField(model_name="conversation", name="customer_gender"),
        migrations.RemoveField(model_name="conversation", name="customer_locale"),
        migrations.RemoveField(model_name="conversation", name="customer_phone"),
        migrations.RemoveField(model_name="conversation", name="customer_username"),
        migrations.RemoveField(model_name="conversation", name="noonce"),
        migrations.RemoveField(model_name="conversation", name="platform_from_id"),
        migrations.RemoveField(model_name="conversation", name="timezone"),
    ]
