# Generated by Django 2.2.1 on 2019-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operator_interface", "0041_conversation_additional_conversation_data")
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="selection",
            field=models.TextField(blank=True, null=True),
        )
    ]
