# Generated by Django 2.2.7 on 2019-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operator_interface", "0044_messageentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="guessed_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
