# Generated by Django 3.0 on 2020-02-08 14:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


def update_conversations(apps, schema_editor):
    Conversation = apps.get_model("operator_interface", "Conversation")
    ConversationPlatform = apps.get_model("operator_interface", "ConversationPlatform")
    for conversation in Conversation.objects.all():
        platform = ConversationPlatform(
            conversation=conversation,
            platform=conversation.platform,
            platform_id=conversation.platform_id,
            additional_platform_data=conversation.additional_conversation_data,
        )
        platform.save()
        for message in conversation.messages.all():
            message.platform = platform
            message.platform_message_id = message.message_id
            message.message_id = uuid.uuid4()
            if message.delivered:
                message.state = "D"
            if message.read:
                message.state = "R"
            message.save()


class Migration(migrations.Migration):
    dependencies = [("operator_interface", "0046_auto_20191222_1736")]

    operations = [
        migrations.CreateModel(
            name="ConversationPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FB", "Facebook"),
                            ("TW", "Twitter"),
                            ("TG", "Telegram"),
                            ("AZ", "Azure"),
                            ("GA", "Actions on Google"),
                            ("TX", "SMS"),
                        ],
                        max_length=2,
                    ),
                ),
                ("platform_id", models.CharField(max_length=255)),
                ("additional_platform_data", models.TextField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operator_interface.Conversation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="platform",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="operator_interface.ConversationPlatform",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="platform_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="state",
            field=models.CharField(
                choices=[
                    ("S", "Sending"),
                    ("D", "Delivered"),
                    ("R", "Read"),
                    ("F", "Failed"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.RunPython(update_conversations),
        migrations.RemoveField(
            model_name="conversation", name="additional_conversation_data"
        ),
        migrations.RemoveField(model_name="conversation", name="platform"),
        migrations.RemoveField(model_name="conversation", name="platform_id"),
        migrations.AlterField(
            model_name="conversation",
            name="agent_responding",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RemoveField(model_name="message", name="conversation"),
        migrations.RemoveField(model_name="message", name="delivered"),
        migrations.RemoveField(model_name="message", name="read"),
    ]
