# Generated by Django 3.0.3 on 2020-03-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0047_auto_20200208_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationplatform',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversationplatform',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TG', 'Telegram'), ('AZ', 'Azure'), ('GA', 'Actions on Google'), ('TX', 'SMS'), ('CH', 'Customer chat'), ('AB', 'Apple Business chat')], max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operator_interface.ConversationPlatform'),
        ),
    ]
