# Generated by Django 3.0.4 on 2020-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0048_auto_20200305_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationplatform',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TG', 'Telegram'), ('AZ', 'Azure'), ('GA', 'Actions on Google'), ('TX', 'SMS'), ('CH', 'Customer chat'), ('AB', 'Apple Business chat'), ('EM', 'Email'), ('WA', 'WhatsApp')], max_length=2),
        ),
    ]
