# Generated by Django 3.0.4 on 2020-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0050_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
