# Generated by Django 3.1.3 on 2020-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0052_message_device_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='as207960_persona_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversationplatform',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TG', 'Telegram'), ('AZ', 'Azure'), ('GA', 'Actions on Google'), ('TX', 'SMS'), ('CH', 'Customer chat'), ('AB', 'Apple Business chat'), ('EM', 'Email'), ('WA', 'WhatsApp'), ('AS', 'AS20790 Messaging')], max_length=2),
        ),
    ]
