# Generated by Django 3.1.3 on 2020-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0053_auto_20201121_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request_live_agent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
