# Generated by Django 3.1.8 on 2021-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_interface', '0054_message_request_live_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
