# Generated by Django 2.2.1 on 2019-08-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("rasa_api", "0002_auto_20190801_1531")]

    operations = [
        migrations.CreateModel(
            name="EnvironmentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rasa_model", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="TestingUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("FB", "Facebook"), ("TW", "Twitter")], max_length=2
                    ),
                ),
                ("platform_id", models.CharField(max_length=255)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rasa_api.EnvironmentModel",
                    ),
                ),
            ],
        ),
    ]
