# Generated by Django 2.2.1 on 2019-08-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rasa_api", "0003_environmentmodel_testinguser")]

    operations = [
        migrations.RenameField(
            model_name="testinguser", old_name="platform_id", new_name="sender_id"
        ),
        migrations.RemoveField(model_name="testinguser", name="platform"),
    ]
