# Generated by Django 2.2.4 on 2019-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_api', '0009_auto_20190816_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinguser',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('TG', 'Telegram'), ('AZ', 'Azure'), ('GA', 'Actions on Google')], max_length=2),
        ),
    ]
