# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "django-keycloak-auth" = pkgs.python37.pkgs.buildPythonPackage rec {
    name = "django-keycloak-auth";
    src = ./../../django-keycloak-auth;
    doCheck = false;
    propagatedBuildInputs = [
      self."Django"
    ];
  };
  "Automat" = super.buildPythonPackage rec {
    pname = "Automat";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl";
      sha256 = "0n3aj4s177dy7ia2ikr5vla60m5y79ll7ym1rygaz644nrkapk7x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."six"
    ];
  };
  "ConfigArgParse" = super.buildPythonPackage rec {
    pname = "ConfigArgParse";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/ea/f0ade52790bcd687127a302b26c1663bf2e0f23210d5281dbfcd1dfcda28/ConfigArgParse-0.14.0.tar.gz";
      sha256 = "149fy4zya0rsnlkvxbbq43cyr8lscb5k4pj1m6n7f1grwcmzwbif";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."PyYAML"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Deprecated" = super.buildPythonPackage rec {
    pname = "Deprecated";
    version = "1.2.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/0e/9d5a1a8cd7130c49334cce7b8167ceda63d6a329c8ea65b626116bc9e9e6/Deprecated-1.2.6-py2.py3-none-any.whl";
      sha256 = "13cgg9b74ygjmz5v60rf0l8sffz8yzg22zc33l6gd25ci9642yxh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wrapt"
    ];
  };
  "Django" = super.buildPythonPackage rec {
    pname = "Django";
    version = "2.2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/9f/a56f7893b1280e5019482260e246ab944d54a9a633a01ed04683d9ce5078/Django-2.2.5-py3-none-any.whl";
      sha256 = "1yn5i1lx7hf09pj8ai2ycy1qllcgf6vrmsd4n21kicl538nlm2hl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
      self."sqlparse"
    ];
  };
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "2.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl";
      sha256 = "0yqwnvqsxf74l4m5ayfv7slkp1a0mi77hv7q10gv5ar72npnrp8l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Pillow" = super.buildPythonPackage rec {
    pname = "Pillow";
    version = "6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/fe/18125dc680720e4c3086dd3f5f95d80057c41ab98326877fc7d3ff6d0ee5/Pillow-6.1.0.tar.gz";
      sha256 = "1pnrsz0f0n0c819v1pdr8j6rm8xvhc9f3kh1fv9xpdp9n5ygf108";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."pytest"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyHamcrest" = super.buildPythonPackage rec {
    pname = "PyHamcrest";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl";
      sha256 = "0814a476zckc3w12zws3n4zk7s0whiij5f2aczwhsizpzl12qrvb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
      self."six"
    ];
  };
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz";
      sha256 = "1r5faspz73477hlbjgilw05xsms0glmsa371yqdd26znqsvg1b81";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Werkzeug" = super.buildPythonPackage rec {
    pname = "Werkzeug";
    version = "0.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl";
      sha256 = "1i355m3957qq35fzz0zz5grjdysswmc78nkhva9qmcajigws3x75";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "aioredis" = super.buildPythonPackage rec {
    pname = "aioredis";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/7f/e8006bc25775124aabf2443255cfc0c5092b9bc0c27f2aa0fc559d19034e/aioredis-1.3.0-py3-none-any.whl";
      sha256 = "0a7yic8vgxnn7pl5xrq48lva833nd284c2v6zvqqdpbsxgmjqc3i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-timeout"
      self."hiredis"
    ];
  };
  "amqp" = super.buildPythonPackage rec {
    pname = "amqp";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/ef/a62ff9dde89e6b75976a746aa5b828ccb3c839ac6fcdc283edd88d7cf90b/amqp-2.5.1-py2.py3-none-any.whl";
      sha256 = "0smjbzfxx5bhkwl56xm7p8ig897rrwv9kpq1rzyzqwd4g6w53n0r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."vine"
    ];
  };
  "argparse" = super.buildPythonPackage rec {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl";
      sha256 = "0533cr5w14da8wdb2q4py6aizvbvsdbk3sj7m1jx9lwznvnlf5n3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asgiref" = super.buildPythonPackage rec {
    pname = "asgiref";
    version = "3.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/39/42344b1060cfb5542eecef3ce6dda3d2d5a89a660716ed5980635985f2a7/asgiref-3.2.2-py2.py3-none-any.whl";
      sha256 = "08xqp5s5msipmyapm736gk2brfhfaf49bx1gch9wm77ldrp75km4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asn1crypto" = super.buildPythonPackage rec {
    pname = "asn1crypto";
    version = "0.24.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl";
      sha256 = "11sfqs4zx8v2nmzgn4bxmidmiwswbk4kxwhfr7irklbfajvxn6ig";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl";
      sha256 = "18wy5w0wk37ikx9n5yc8s9746bgqz3wdddbc1d6jfz98glcwm4a2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "atomicwrites" = super.buildPythonPackage rec {
    pname = "atomicwrites";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl";
      sha256 = "1d0id3y2hbnwjfm8hf6spfzpya5qdak2qk3y4alinp9cxcq2qiq3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "19.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl";
      sha256 = "0ybaycx149w1q2fqkjv119l83vx5115l8167bv5y2b9rxprdph39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "autobahn" = super.buildPythonPackage rec {
    pname = "autobahn";
    version = "19.9.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/f3/42e681a0b1234f1ffdcaf548afe03685ede21ae259de2ea6ad60c83faead/autobahn-19.9.3-py2.py3-none-any.whl";
      sha256 = "03zcwcrjqfanfzpy4v3048him7qicpxchkk1w8pgqiamvnyqqs17";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
      self."txaio"
    ];
  };
  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/60/f2af68eb046c5de5b1fe6dd4743bf42c074f7141fe7b2737d3061533b093/Babel-2.7.0-py2.py3-none-any.whl";
      sha256 = "1asqc722hrksgwyliflhdaryzd7qjmvasf2vna355idpdh8fd4mg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };
  "billiard" = super.buildPythonPackage rec {
    pname = "billiard";
    version = "3.6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/bb/2a016ac912fca48e06ff5a662407f3d1681aa47df97fb19feba7cc931ee1/billiard-3.6.1.0-py3-none-any.whl";
      sha256 = "10pc06cz9l6hhhwm7nkakm8agmqrvjg4vgfg804limjggi7cpbq1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cachetools" = super.buildPythonPackage rec {
    pname = "cachetools";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl";
      sha256 = "1bhp0lwd5zcp1v59y4vjin4jr37889cpqb9slsncavfkq2hnd0j2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "celery" = super.buildPythonPackage rec {
    pname = "celery";
    version = "4.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/a1/a3dd9d8bfa09156ec2cba37f90accf35c0f4ecc3980d96cb4fb99e56504b/celery-4.3.0-py2.py3-none-any.whl";
      sha256 = "1ghryagdn746zbzzqf4d6ra5f7s9c88fw97grwb3mr77g9v5d3jj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."billiard"
      self."kombu"
      self."pytz"
      self."vine"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2019.9.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl";
      sha256 = "1vvc1sssixxgcx719hpibg4zwkv0valbn9ndk87g1p3xf9s7qz7x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz";
      sha256 = "0x075521fxwv0mfp4cqzk7lvmw4n94bjw601qkcv314z5s182704";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "channels" = super.buildPythonPackage rec {
    pname = "channels";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/4d/e2e4efda2804bdb9151177035bd48c1e88aad300b7e40e11cf1c7ca82030/channels-2.3.0-py2.py3-none-any.whl";
      sha256 = "0j67ybr2zcpmxzqy24rcc8b2m0s7s70xa51vd4sdzwd67959wa6h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Django"
      self."asgiref"
      self."daphne"
    ];
  };
  "channels-redis" = super.buildPythonPackage rec {
    pname = "channels-redis";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a4/c72fb980e688cf7775b4889c8d1c75d4be1442f3b4ae8e4364d23514d3f1/channels_redis-2.4.0-py2.py3-none-any.whl";
      sha256 = "1jdr70hl2h46yjybn0lnknc1z332k7429v28751s540nhnkzj98f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aioredis"
      self."asgiref"
      self."channels"
      self."msgpack"
    ];
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "3.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
      sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl";
      sha256 = "04rbcbf5p4kdc7ghlsddxrnglsvk4rsmzphnlxyfdfcmcdg0cd93";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coloredlogs" = super.buildPythonPackage rec {
    pname = "coloredlogs";
    version = "10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/0f/7877fc42fff0b9d70b6442df62d53b3868d3a6ad1b876bdb54335b30ff23/coloredlogs-10.0-py2.py3-none-any.whl";
      sha256 = "1y7gg45a2knibrxsx8nr8wnbcz7r2j6rx23c3g1mk9fm8bix5yil";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."humanfriendly"
    ];
  };
  "constantly" = super.buildPythonPackage rec {
    pname = "constantly";
    version = "15.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl";
      sha256 = "0pbwnc78hi3y7gizcjrqdqbslij0fcyjjxnxszq866m5n7bajbyx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "2.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz";
      sha256 = "1inlnr36kl36551c9rcad99jmhk81v33by3glkadwdcgmi17fd76";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."asn1crypto"
      self."cffi"
      self."six"
    ];
  };
  "daphne" = super.buildPythonPackage rec {
    pname = "daphne";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/43/2e/9b2498d30d7397a27aae5c67f194a9a002be406bdb5a1cb9699de9bb1878/daphne-2.3.0-py2.py3-none-any.whl";
      sha256 = "1mdd1ljjd0qb2mm5n4l1kzhmpjw00ipr316yswkv3rask5m2ibiw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."autobahn"
      self."twisted"
    ];
  };
  "dateutils" = super.buildPythonPackage rec {
    pname = "dateutils";
    version = "0.6.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/11/246237ce2a1dd87ffebef0e430033f877b31dd208b281914d4fd3c531ee7/dateutils-0.6.6.tar.gz";
      sha256 = "0wcaxpn9p9dbnz5lalg04yjp5aclymg9zycixmwsras3sxvqwjn9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argparse"
      self."python-dateutil"
      self."pytz"
    ];
  };
  "django-cors-headers" = super.buildPythonPackage rec {
    pname = "django-cors-headers";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/97/4be47519ab0f42bfec76fa94c2dbe9870e171a372f61a70ee1abba045485/django_cors_headers-3.1.0-py3-none-any.whl";
      sha256 = "0kww3rmwchbbdkdqv7rq88kyijfs7amc02pyhdw5gg50nc4j5cg4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Django"
    ];
  };
  "django-phonenumber-field" = super.buildPythonPackage rec {
    pname = "django-phonenumber-field";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/e7/9beb116b62165bf7e6ed32b76ad1e3246aa1be9592cfae7de0e400bb58c5/django_phonenumber_field-3.0.1-py3-none-any.whl";
      sha256 = "0pkw93hkx4d9njw2d1bd4xkg8kzs45189n9b87njyn1875r9zc8s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Django"
      self."babel"
    ];
  };
  "djsingleton" = super.buildPythonPackage rec {
    pname = "djsingleton";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/bd/93663a85cf543b9a66bc600d7a76fcffd9d2af94a6afcda83cd80e9cb783/djsingleton-1.0.1-py2.py3-none-any.whl";
      sha256 = "0bvcbad9yscgi6mpmfdrk9b2zgk6952b30jaz0d7iy6hychzbgax";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ecdsa" = super.buildPythonPackage rec {
    pname = "ecdsa";
    version = "0.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/a8/8aa68e70959e1287da9154e5164bb8bd5dd7025e41ae54e8d177b8d165c9/ecdsa-0.13.2-py2.py3-none-any.whl";
      sha256 = "0z35p7gvy1d3dvy43yc1p28qn5xclrcf3412827svb3mgr97xh90";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "flask" = super.buildPythonPackage rec {
    pname = "flask";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl";
      sha256 = "1xhk7glj7a1rylk5csck0apgmmc33yrsbn7m1izczmlks5pmmss5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Jinja2"
      self."Werkzeug"
      self."click"
      self."itsdangerous"
    ];
  };
  "flask-cors" = super.buildPythonPackage rec {
    pname = "flask-cors";
    version = "3.0.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/38/e68b11daa5d613e3a91e4bf3da76c94ac9ee0d9cd515af9c1ab80d36f709/Flask_Cors-3.0.8-py2.py3-none-any.whl";
      sha256 = "16nns5dd4vrs0zp06c0v9ghbw6nknssq5l495pzvqsqfcq0p5ngl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."flask"
      self."six"
    ];
  };
  "future" = super.buildPythonPackage rec {
    pname = "future";
    version = "0.17.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz";
      sha256 = "1f2rlqn9rh7adgir52dlbqz69gsab44x0mlm8gf1cs7xvhv54137";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fuzzywuzzy" = super.buildPythonPackage rec {
    pname = "fuzzywuzzy";
    version = "0.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl";
      sha256 = "0m7j4rlnwqs0723cdqxyqpdlw54qanjm7nhpm91jg3b5yjrw1iss";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gevent" = super.buildPythonPackage rec {
    pname = "gevent";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/27/6c49b70808f569b66ec7fac2e78f076e9b204db9cf5768740cff3d5a07ae/gevent-1.4.0.tar.gz";
      sha256 = "1lchr4akw2jkm5v4kz7bdm4wv3knkfhbfn9vkkz4s5yrkcxzmdqy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."greenlet"
    ];
  };
  "google-auth" = super.buildPythonPackage rec {
    pname = "google-auth";
    version = "1.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl";
      sha256 = "1v8r67ciy8r8795fjngxa5yrmjyzsh4xzc6wq8f4sb7x0dl5yw10";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cachetools"
      self."pyasn1-modules"
      self."rsa"
      self."six"
    ];
  };
  "greenlet" = super.buildPythonPackage rec {
    pname = "greenlet";
    version = "0.4.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/e8/b30ae23b45f69aa3f024b46064c0ac8e5fcb4f22ace0dca8d6f9c8bbe5e7/greenlet-0.4.15.tar.gz";
      sha256 = "1g4g1wwc472ds89zmqlpyan3fbnzpa8qm48z3z1y6mlk44z485ll";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gunicorn" = super.buildPythonPackage rec {
    pname = "gunicorn";
    version = "19.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl";
      sha256 = "0w947i3p0b7y1qxkpfj573s6lvf7r52rynayvyjkcyqmni00p3ma";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "hiredis" = super.buildPythonPackage rec {
    pname = "hiredis";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/e0/c160dbdff032ffe68e4b3c576cba3db22d8ceffc9513ae63368296d1bcc8/hiredis-1.0.0.tar.gz";
      sha256 = "158pymdlnv4d218w66i8kzdn4ka30l1pdwa0wyjh16bj10zraz79";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "http-ece" = super.buildPythonPackage rec {
    pname = "http-ece";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/1a/60ccc29fccd4789b7cada188b114185e8a5d63aba0d93262adbbe776cfe5/http_ece-1.1.0.tar.gz";
      sha256 = "1y5ln09ji4dwpzhxr77cggk02kghq7lql60a6969a5n2lwpvqblk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."nose"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
    ];
  };
  "humanfriendly" = super.buildPythonPackage rec {
    pname = "humanfriendly";
    version = "4.18";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl";
      sha256 = "07arwnyin4liavbhvp5v37v1kfcafsv3q3m2qdxjwy3gml87n193";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "hyperlink" = super.buildPythonPackage rec {
    pname = "hyperlink";
    version = "19.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl";
      sha256 = "0kyh44vnb7mykj4qr3vdiskab35ilgnsc850apw096q3xf7k0jmb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl";
      sha256 = "0g2agqpl6ilwgwcsrxmbhx84hvb8zjlpvpy36xsi3yp6i1hpz2za";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "0.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl";
      sha256 = "1brrppl17a672z5qimlgzh4ba9rf5207fws5q5ws2fkzfxwqmwfm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "incremental" = super.buildPythonPackage rec {
    pname = "incremental";
    version = "17.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl";
      sha256 = "17vb81hndavl36q774ck8ir8kqlk9pblhpqp96ik3wnxdlj14zki";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "inflect" = super.buildPythonPackage rec {
    pname = "inflect";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/02/e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-none-any.whl";
      sha256 = "0zmbblhvwfwz4dkia5dkjy8ixd78645h1kxjm27aknrx0hdnfax8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "itsdangerous" = super.buildPythonPackage rec {
    pname = "itsdangerous";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl";
      sha256 = "0jfp17fv977gv3lm78c4jyyrlpjw5qp65df8k3mkxckw0jr728mi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kombu" = super.buildPythonPackage rec {
    pname = "kombu";
    version = "4.6.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/22/58104fd214fb32008f2f4d64a1918c81e353f23e7beee9605674f9ecd6b2/kombu-4.6.4-py2.py3-none-any.whl";
      sha256 = "13qbf451x654i9di7g54k2v3dcnxml7km5xh712rkhxkbv3ls9sm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
      self."importlib-metadata"
    ];
  };
  "mastercard-oauth1-signer" = super.buildPythonPackage rec {
    pname = "mastercard-oauth1-signer";
    version = "1.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/ae/a8dd4bf958a3988dc4e26530fbd576499e29ffc153529031d74f77bcfba4/mastercard_oauth1_signer-1.1.3-py3-none-any.whl";
      sha256 = "0vnbj102l5pvpglvdcykdsv12j9gam7xa2s9m4klsmwb540cpv36";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Deprecated"
      self."cryptography"
      self."pyOpenSSL"
      self."requests"
      self."urllib3"
    ];
  };
  "more-itertools" = super.buildPythonPackage rec {
    pname = "more-itertools";
    version = "7.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl";
      sha256 = "1i30pck2xhfxqy4z0j5bq6xf3cjjvqp2z6vjq08hckxcdnqc9f4j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "msgpack" = super.buildPythonPackage rec {
    pname = "msgpack";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/0a/de673c1c987f5779b65ef69052331ec0b0ebd22958bda77a8284be831964/msgpack-0.6.2.tar.gz";
      sha256 = "0c0q3vx0x137567msgs5dnizghnr059qi5kfqigxbz26jf2jyg7a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mysqlclient" = super.buildPythonPackage rec {
    pname = "mysqlclient";
    version = "1.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz";
      sha256 = "1379hab7spjp9v5fypqgy0b8vr8vnalxahm9hcsxvj2xbb2pqwww";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nose" = super.buildPythonPackage rec {
    pname = "nose";
    version = "1.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl";
      sha256 = "1b2kgk8nylcp5sspfx5y8pcxdbs5ryxng9il9fcm331z8k6cdxwz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "oauthlib" = super.buildPythonPackage rec {
    pname = "oauthlib";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl";
      sha256 = "1si8jdy15j83id7fy6rnwhw3dxanjcp0gc8x7xik43p2rgb4r26z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl";
      sha256 = "026i9vg4vz52rgz717l7arya2g1amc4ayyv7y7gg6qfpqr2iamfr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
      self."six"
    ];
  };
  "phonenumbers" = super.buildPythonPackage rec {
    pname = "phonenumbers";
    version = "8.10.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/5b/f979988330e05cee4989ea0350346c3c02566e0723fdf2d46c994e60ecb8/phonenumbers-8.10.19-py2.py3-none-any.whl";
      sha256 = "00s52mm672h7r98fpmjgr4wijf0581i016ja5c5wr59kk25q8f23";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "0.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl";
      sha256 = "1rn39rg4ncng4m5rdrn1hn8s2nl4fsj2sa1kl2s3a7df39hbgd0d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "psycopg2-binary" = super.buildPythonPackage rec {
    pname = "psycopg2-binary";
    version = "2.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/91/91911be01869fa877135946f928ed0004e62044bdd876c1e0f12e1b5fb90/psycopg2-binary-2.8.3.tar.gz";
      sha256 = "0vmxr94i36mksy6w8w5yfx8sdphypji56sxjxjdn193q0qbwqdyd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py" = super.buildPythonPackage rec {
    pname = "py";
    version = "1.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl";
      sha256 = "1ylkczijmfk6vrv8dj4sdfdmpwf38yhs6rkplb783cz5mramgxk4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py-vapid" = super.buildPythonPackage rec {
    pname = "py-vapid";
    version = "1.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/c9/64ab806f2e99b35039ad8c64c5dd0a53eb1e56f1b8b637f13614870523a5/py-vapid-1.7.0.tar.gz";
      sha256 = "0jjnw92bwklzvnrwlcj0kwba7a0vs21m14g264ydbiyxf0r7l183";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."nose"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
    ];
  };
  "pyOpenSSL" = super.buildPythonPackage rec {
    pname = "pyOpenSSL";
    version = "19.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl";
      sha256 = "1rnislyzs93nnqxfh0qd1kvl32rddxk4n08mf0azq42bsl5969y7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/71/8f0d444e3a74e5640a3d5d967c1c6b015da9c655f35b2d308a55d907a517/pyasn1-0.4.7-py2.py3-none-any.whl";
      sha256 = "137xpv3xl28w71hzywkbzyxw01dw4ba5v189bqc0n3sknplavkb2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1-modules" = super.buildPythonPackage rec {
    pname = "pyasn1-modules";
    version = "0.2.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/70/e5ea8afd6d08a4b99ebfc77bd1845248d56cfcf43d11f9dc324b9580a35c/pyasn1_modules-0.2.6-py2.py3-none-any.whl";
      sha256 = "1h741k9jcw9ab908w3pd32zdp546s1zxiwszi1nb5w91salrj0g3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyjwt" = super.buildPythonPackage rec {
    pname = "pyjwt";
    version = "1.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl";
      sha256 = "03imf7mfzkbwzf3w1bpckcf79pba1jq87flrdc84sij054yclvjw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl";
      sha256 = "1d18n2lq47808yxm55j85q6v2s0r2v18fkhfbbbgbfq357qqscyr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "5.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/cd/3871df1ef4cec65b664738fafedf999cdac33b193367b3e313dd569c169a/pytest_runner-4.5.1-py2.py3-none-any.whl";
      sha256 = "1xlm7zh39l0y76m5c45djml6yrql6sfcbglh07gm8arkf693sp8p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."importlib-metadata"
      self."more-itertools"
      self."packaging"
      self."pluggy"
      self."py"
      self."wcwidth"
    ];
  };
  "pytest-runner" = super.buildPythonPackage rec {
    pname = "pytest-runner";
    version = "4.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/cd/3871df1ef4cec65b664738fafedf999cdac33b193367b3e313dd569c169a/pytest_runner-4.5.1-py2.py3-none-any.whl";
      sha256 = "1xlm7zh39l0y76m5c45djml6yrql6sfcbglh07gm8arkf693sp8p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-Levenshtein" = super.buildPythonPackage rec {
    pname = "python-Levenshtein";
    version = "0.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz";
      sha256 = "1c9ybqcja31nghfcc8xxbbz9h60s9qi12b9hr4jyl69xbvg12fh3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl";
      sha256 = "1yzj7m4h5babisvqac674xx82a8gd7ynxqhm2rwj7mpf9b3q8rby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-jose" = super.buildPythonPackage rec {
    pname = "python-jose";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/da/c0dcc5e7a98a53440b8db3cf9771345fa696754f79e8734ea59123f7d734/python_jose-3.0.1-py2.py3-none-any.whl";
      sha256 = "077zx8y85xy1phap0b74lyfs7942m09k4v142wpyaq75iycisw19";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ecdsa"
      self."future"
      self."rsa"
      self."six"
    ];
  };
  "python-keycloak-client" = super.buildPythonPackage rec {
    pname = "python-keycloak-client";
    version = "0.2.3.dev0";
    src = fetchgit {
      url = "https://github.com/Peter-Slump/python-keycloak-client.git";
      rev = "5506119627270d88e685f8fd29b1f3c31f70c347";
      sha256 = "1ff6kv4zm4c27ps9bi6piff7ivfks6rkp6fbdbpnk4s1w87zirh5";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."pytest"
    ];
    nativeBuildInputs = [
      self."pytest-runner"
    ];
    propagatedBuildInputs = [
      self."python-jose"
      self."requests"
    ];
  };
  "python-magic" = super.buildPythonPackage rec {
    pname = "python-magic";
    version = "0.4.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl";
      sha256 = "0x8khcb0695rzf695v0xvcqb2h4mh0ks0gw0si4nrbjjmp7lsrzj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2019.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl";
      sha256 = "1izhlrh3mfcvmkjqqc12j2yymddsgnvsljhif5f2vkd401sxb568";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pywebpush" = super.buildPythonPackage rec {
    pname = "pywebpush";
    version = "1.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/3f/5d91840bff754fe538c87912b48dbc81c9990607acc27bab4ca55f37b24e/pywebpush-1.10.0.tar.gz";
      sha256 = "1mpb7bclw3kpi45fbd3s4fwgxlljdqsxavzi0mj5qnbbiiipx2yy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."cryptography"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."http-ece"
      self."py-vapid"
      self."requests"
    ];
  };
  "rasa-sdk" = super.buildPythonPackage rec {
    pname = "rasa-sdk";
    version = "1.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/ba/01de9500cb3f625ac267ea67b6186f9b71a93a4108df0a6646f094c49792/rasa_sdk-1.3.2-py2.py3-none-any.whl";
      sha256 = "0nifzw1rwgdlh05yai9n5h35k2xnchrj6zhdhnfrvv5d3g8p4874";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ConfigArgParse"
      self."coloredlogs"
      self."flask"
      self."flask-cors"
      self."future"
      self."gevent"
      self."requests"
      self."six"
    ];
  };
  "redis" = super.buildPythonPackage rec {
    pname = "redis";
    version = "3.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/64/b1e90af9bf0c7f6ef55e46b81ab527b33b785824d65300bb65636534b530/redis-3.3.8-py2.py3-none-any.whl";
      sha256 = "0xc2mq2cn20cr1w7glz0dmy1jl30182qdxswvpbhs6q3d4bja165";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl";
      sha256 = "0cabdkf52181iks919g9hn0bn4vz39yhs7pw3ikqqn8grlpjkxcw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
  };
  "requests-oauthlib" = super.buildPythonPackage rec {
    pname = "requests-oauthlib";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl";
      sha256 = "0h2iwb3n3d6xplbdnf6sd523kas56y9nygd69ws6pg1v5s7hrvfk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."oauthlib"
      self."requests"
    ];
  };
  "rsa" = super.buildPythonPackage rec {
    pname = "rsa";
    version = "4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl";
      sha256 = "0rmy24185fknzg40c81pislmhjc169myfb3a43mrxv7i1xq4bfhl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "sentry-sdk" = super.buildPythonPackage rec {
    pname = "sentry-sdk";
    version = "0.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/c2/845d503adb168fcd276a54ac7e5a4fab18d8ed83cf8ad8fba6599eb6ca9c/sentry_sdk-0.12.2-py2.py3-none-any.whl";
      sha256 = "17kxkapp6azg0d2rvxzaa2h3fqzizz9x16gcrwyqxh8cqhwva5mb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."urllib3"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl";
      sha256 = "073nyd09fqi2xwalmsi2lf8lrwnma85hscs84iaizcam0ngq0l1k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sqlparse" = super.buildPythonPackage rec {
    pname = "sqlparse";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl";
      sha256 = "0xw19y1hl4qgs6ifibgfbaqs3n87rsldf12mzxypw4disjwfdbs0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "twisted" = super.buildPythonPackage rec {
    pname = "twisted";
    version = "19.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/31/3855dcacd1d3b2e60c0b4ccc8e727b8cd497bd7087d327d81a9f0cbb580c/Twisted-19.7.0.tar.bz2";
      sha256 = "17d3hnxv9qndagzz63mdpyk99xj63p9gq586vjn0rxk8cl197nym";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."incremental"
    ];
    propagatedBuildInputs = [
      self."Automat"
      self."PyHamcrest"
      self."attrs"
      self."constantly"
      self."hyperlink"
      self."zope.interface"
    ];
  };
  "txaio" = super.buildPythonPackage rec {
    pname = "txaio";
    version = "18.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl";
      sha256 = "1xbfcb3k3d30rzmg125a7rfslp0snxyk6gml27hzyn6c6ba3bcmn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.25.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl";
      sha256 = "163kbfjfdkikip15l0f7i9905imaiz8981cr11k79rnnpvzlds9x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "vine" = super.buildPythonPackage rec {
    pname = "vine";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl";
      sha256 = "1bwq7yx13npsnil8wlljhvvndnfs4pp47mf8jlh6zzfiav64fjga";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl";
      sha256 = "0z6yi9wgxisnsz14c5zpz123bd2rslg7cgsmcjl40yxg4lcygszl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wheel" = super.buildPythonPackage rec {
    pname = "wheel";
    version = "0.33.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl";
      sha256 = "0a5gkxdnhdn8jalrxppx6350xw7h434sf51av4n2xkxysdiignpl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz";
      sha256 = "1q81762dgsgrd12f8qc39zk8s5wll3m5xc32jdmlf6cls4gh4njn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl";
      sha256 = "0d9kggxfnvdf51ljciy7mm29mcvan33lljq0f79i4fzly7lh6sgh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."more-itertools"
    ];
  };
  "zope.event" = super.buildPythonPackage rec {
    pname = "zope.event";
    version = "4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/96/361edb421a077a4c208b4a5c212737d78ae03ce67fbbcd01621c49f332d1/zope.event-4.4-py2.py3-none-any.whl";
      sha256 = "1ryawlzi3lpzi3fh3i38zvn8ncx33vhklc7m8mxrk86mbwb7vsfq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "zope.interface" = super.buildPythonPackage rec {
    pname = "zope.interface";
    version = "4.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/d0/c9d16bd5b38de44a20c6dc5d5ed80a49626fafcb3db9f9efdc2a19026db6/zope.interface-4.6.0.tar.gz";
      sha256 = "1rgh2x3rcl9r0v0499kf78xy86rnmanajf4ywmqb943wpk50sg8v";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [
      self."zope.event"
    ];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
}
