# Generated by Django 2.1.3 on 2019-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_auto_20190518_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='maps_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
