# Generated by Django 2.2.1 on 2019-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0006_ipadrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadrepair',
            name='repair_time',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iphonerepair',
            name='repair_time',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
