# Generated by Django 2.2.4 on 2019-09-03 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0010_auto_20190808_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockForm',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.PhoneUnlock')),
            ],
        ),
    ]
