# Generated by Django 2.2.5 on 2019-09-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0012_auto_20190903_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlockform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='unlockform',
            name='name',
        ),
        migrations.AddField(
            model_name='unlockform',
            name='customer_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
