# Generated by Django 2.2.7 on 2019-11-09 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkingState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
