# Generated by Django 2.2.1 on 2019-07-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("payment", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="environment",
            field=models.CharField(
                choices=[("T", "Test"), ("L", "Live")], default="T", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.Customer",
            ),
        ),
    ]
