# Generated by Django 2.2.1 on 2019-07-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("payment", "0002_auto_20190729_1134")]

    operations = [
        migrations.CreateModel(
            name="ThreeDSData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oneTime3DsToken", models.TextField()),
                ("redirectURL", models.TextField()),
                ("orderId", models.TextField()),
                ("sessionId", models.CharField(max_length=255)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.Payment",
                    ),
                ),
            ],
        )
    ]
