# Generated by Django 2.2.1 on 2019-07-30 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_threedsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedsdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
