# Generated by Django 2.2.1 on 2019-07-31 11:29

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190731_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(default=payment.models.make_token, editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
